### ISSUE TITLE
Introduction to Material Desing  Key Colors

### ISSUE THREAD

**Issue by khalekuzzamancse** [khalekuzzamancse/UI_Design_System_Samples#3]
### Tasks 
- [ ] Explore the concept of "Introduction to Color Schemes"
- [ ] Examine the significance of choosing a key color
- [ ] Investigate the rationale behind selecting only five colors as key color
